@hostname = http://localhost:5001

###
post {{hostname}}/signup
Content-Type: application/json

{
  "name":"prakash jayawal",
  "email":"prj11111@gmail.com",
  "password":"abc",
  "age":20,
  "lng":20.23819623232004,
  "lat":72.9883987380813
}

