@hostname = http://localhost:5001

###
post {{hostname}}/signup
Content-Type: application/json

{
  "name":"prakash jayawal",
  "email":"1234111151@gmail.com",
  "password":"abc",
  "age":20,
  "lat":26.373867896137224,
  "lng": 77.6883667402968
}

# 28.5355° N, 77.3910 UP



# Rajasthan
# 26.4833° N, 76.7340° E ggc

# Delhi Cannaught palace
# 28.6304° N, 77.2177° E

# Hyderabad
# 17.3850° N, 78.4867° E